#!/bin/bash
# Manual Image Download Script for Muchnik Elder Law
# Run this script in a browser environment or use a browser extension to download

echo "=== Muchnik Elder Law - Image Download List ==="
echo ""
echo "Please download these images manually from a browser:"
echo ""
echo "1. LOGO:"
echo "   URL: https://muchnikelderlaxw.com/wp-content/uploads/2021/11/Muchnik-Elder-Law-Logo-150x86.png"
echo "   Save to: public/images/logo.png"
echo ""
echo "2. TEAM PHOTOS:"
echo "   - Kirill Muchnik:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2019/12/180530-Kirill.jpg"
echo "     Save to: public/images/team/kirill-muchnik.jpg"
echo ""
echo "   - Leslie Langworthy:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2019/12/Leslie-M.-Langworthy-Esq-731x1024.jpg"
echo "     Save to: public/images/team/leslie-langworthy.jpg"
echo ""
echo "   - Gary Johnson:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2019/12/Gary-W.-Johnson-Esq-731x1024.jpg"
echo "     Save to: public/images/team/gary-johnson.jpg"
echo ""
echo "3. HERO/PRACTICE AREA IMAGES:"
echo "   - Elderly Couple:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2019/12/elderly-couple.jpg"
echo "     Save to: public/images/hero/elderly-couple.jpg"
echo ""
echo "   - Family Documents:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2019/12/IMGnewbrif-1024x778.jpg"
echo "     Save to: public/images/hero/family-documents.jpg"
echo ""
echo "   - Family in Woods:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2019/12/family-in-the-woods.jpg"
echo "     Save to: public/images/hero/family-woods.jpg"
echo ""
echo "   - Elder Law:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2020/10/Depositphotos_281430174_xl-2015-1-1024x683.jpg"
echo "     Save to: public/images/practice-areas/elder-law.jpg"
echo ""
echo "   - Estate Planning:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2020/10/Depositphotos_23557569_xl-2015-1024x683.jpg"
echo "     Save to: public/images/practice-areas/estate-planning.jpg"
echo ""
echo "   - Estate Trust:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2021/12/Depositphotos_210660438_XL.jpg"
echo "     Save to: public/images/practice-areas/estate-trust.jpg"
echo ""
echo "   - Special Needs:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2021/11/shutterstock_1007409607.jpg"
echo "     Save to: public/images/practice-areas/special-needs.jpg"
echo ""
echo "   - Guardianships:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2021/11/shutterstock_1108958093.jpg"
echo "     Save to: public/images/practice-areas/guardianships.jpg"
echo ""
echo "   - Real Estate:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2021/11/tierra-mallorca-rgJ1J8SDEAY-unsplash.jpg"
echo "     Save to: public/images/practice-areas/real-estate.jpg"
echo ""
echo "   - About Hero:"
echo "     URL: https://muchnikelderlaw.com/wp-content/uploads/2019/12/eyeglasses-bokeh.jpg"
echo "     Save to: public/images/about/about-hero.jpg"
echo ""
echo "=== Alternative: Use Unsplash/Pexels for placeholder images ==="
echo "You can use free stock photos as placeholders until you get the originals"
